server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jsbase?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.shimao.jsbase.entity